# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-24
version:      0.01
version_from: lib/Acme/24.pm
installdirs:  site
requires:
    LWP::Simple:                   0
    XML::RSSLite:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
